In [ ]:
1️⃣ np.array()

In [1]:
#Purpose: Create a NumPy array.
import numpy as np

arr = np.array([1, 2, 3, 4])
print(arr)


[1 2 3 4]


In [ ]:
2️⃣ np.arrange()

In [2]:
#Purpose: Create evenly spaced values within a range (like range() in Python but returns an array).
    
arr = np.arange(0, 10, 2)
print(arr)

[0 2 4 6 8]


In [ ]:
3️⃣ np.linspace()

In [3]:
#Purpose: Create an array with evenly spaced numbers between two limits.

arr = np.linspace(0, 1, 5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
4️⃣ np.zeros() / np.ones()

In [4]:
#Purpose: Create arrays filled with zeros or ones.

zeros = np.zeros((2, 3))
ones = np.ones((2, 3))

print(zeros)
print(ones)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
5️⃣ np.eye()

In [5]:
#Purpose: Create an identity matrix.

arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
6️⃣ np.random.rand() / np.random.randn()

In [6]:
#Purpose: Generate random arrays.
#rand() → uniform distribution
#randn() → normal distribution


print(np.random.rand(2, 3))
print(np.random.randn(2, 3))

[[0.56739546 0.5729311  0.75716949]
 [0.8593631  0.38488848 0.80805481]]
[[-1.25311168  0.78102311  0.51120907]
 [-0.48627242 -0.70230959 -0.9399792 ]]


In [ ]:
7️⃣ arr.reshape()

In [7]:
#Purpose: Change the shape of an array.

arr = np.arange(6)
reshaped = arr.reshape(2, 3)
print(reshaped)

[[0 1 2]
 [3 4 5]]


In [ ]:
8️⃣ arr.ndim, arr.shape, arr.size

In [8]:
#Purpose: Get number of dimensions, shape, and total elements.

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.ndim)   # Number of dimensions
print(arr.shape)  # Shape (rows, columns)
print(arr.size)   # Total elements

2
(2, 3)
6


In [ ]:
9️⃣ np.concatenate()

In [9]:
#Purpose: Join two or more arrays.

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.concatenate((a, b)))

[1 2 3 4 5 6]


In [ ]:
🔟 np.vstack() / np.hstack()

In [10]:
#Purpose: Stack arrays vertically or horizontally.

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.vstack((a, b)))
print(np.hstack((a, b)))

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [ ]:
1️⃣1️⃣ arr.T

In [11]:
#Purpose: Transpose of an array (rows → columns).
    
arr = np.array([[1, 2], [3, 4]])
print(arr.T)

[[1 3]
 [2 4]]


In [ ]:
1️⃣2️⃣ np.sum(), np.mean(), np.std()

In [12]:
#Purpose: Basic statistics.

arr = np.array([1, 2, 3, 4])
print(np.sum(arr))
print(np.mean(arr))
print(np.std(arr))

10
2.5
1.118033988749895


In [ ]:
1️⃣3️⃣ np.min(), np.max(), np.argmin(), np.argmax()

In [13]:
#Purpose: Find min/max values and their indices.

arr = np.array([4, 8, 1, 6])
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))
print(np.argmax(arr))

1
8
2
1


In [ ]:
1️⃣4️⃣ np.sqrt(), np.exp(), np.log()

In [14]:
#Purpose: Element-wise math operations.

arr = np.array([1, 4, 9])
print(np.sqrt(arr))
print(np.exp(arr))
print(np.log(arr))

[1. 2. 3.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03]
[0.         1.38629436 2.19722458]


In [ ]:
1️⃣5️⃣ np.dot() / np.matmul()

In [15]:
#Purpose: Matrix multiplication.
    
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(np.dot(a, b))

[[19 22]
 [43 50]]


In [ ]:
1️⃣6️⃣ np.unique()

In [17]:
#Purpose: Find unique elements.

arr = np.array([1, 2, 2, 3, 3, 3])
print(np.unique(arr))

[1 2 3]


In [ ]:
1️⃣7️⃣ np.sort()

In [18]:
#Purpose: Sort an array.

arr = np.array([3, 1, 4, 2])
print(np.sort(arr))

[1 2 3 4]


In [ ]:
1️⃣8️⃣ np.where()

In [19]:
#Purpose: Conditional selection.

arr = np.array([10, 20, 30, 40])
print(np.where(arr > 20))

(array([2, 3]),)


In [ ]:
1️⃣9️⃣ np.concatenate() vs np.append()

In [20]:
#Purpose: Append adds elements to an array.

arr = np.array([1, 2, 3])
print(np.append(arr, [4, 5]))

[1 2 3 4 5]


In [ ]:
2️⃣0️⃣ np.delete()

In [21]:
#Purpose: Delete elements from array

arr = np.array([10, 20, 30, 40])
print(np.delete(arr, 1))

[10 30 40]


In [ ]:
2️⃣1️⃣ np.reshape() vs np.ravel() vs np.flatten()

In [22]:
#Purpose:
#reshape() → Changes shape
#Travel() / flatten() → Converts to 1D

arr = np.array([[1, 2], [3, 4]])
print(arr.ravel())
print(arr.flatten())

[1 2 3 4]
[1 2 3 4]


In [ ]:
2️⃣2️⃣ np.save() / np.load()

In [23]:
#Purpose: Save and load NumPy arrays.

arr = np.array([1, 2, 3])
np.save('my_array.npy', arr)
loaded = np.load('my_array.npy')
print(loaded)

[1 2 3]


In [ ]:
2️⃣3️⃣ np.all() / np.any()

In [24]:
#Purpose: Logical checks.

arr = np.array([1, 0, 3])
print(np.all(arr))  # True if all non-zero
print(np.any(arr))  # True if any non-zero

False
True


In [ ]:
2️⃣4️⃣ np.clip()
Purpose: Limit array values between given bounds.

